site_name: 'vizno'
site_description: 'Visual layout for python.'
site_author: 'Victor Benichoux'

nav:
  - Index: 'index.md'
  - Widgets: 'renderers.md'
  - Rendering: 'rendering.md'
  - CLI: 'cli.md'
  
theme:
  name: 'material'
  logo: 'vizno.svg'
  favicon: vizno.svg
  icon:
    repo: fontawesome/brands/github

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - codehilite
  - meta
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  # - git-revision-date-localized

repo_name: 'victorbenichoux/vizno'
repo_url: 'https://github.com/victorbenichoux/vizno'
